spring.application.name=Trabalho_Spring_Boot

# configs do postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/trabalho_web
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=skraba352

server.port=8081

# jpa
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true